// <auto-generated />
using System;
using LeasingCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeasingCore.Migrations.ApplicationDb
{
    [DbContext(typeof(LeasingContext))]
    [Migration("20190112003228_anotherone")]
    partial class anotherone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeasingCore.Models.Assortment", b =>
                {
                    b.Property<int>("AssortmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssortmentBrand")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("AssortmentName")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<decimal>("AssortmentPrice");

                    b.Property<int>("ParamId");

                    b.HasKey("AssortmentId");

                    b.HasIndex("ParamId");

                    b.ToTable("Assortments");
                });

            modelBuilder.Entity("LeasingCore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LeasingCore.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyHeadquarters")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CompanyNIP")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CompanyId");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("LeasingCore.Models.Leasing", b =>
                {
                    b.Property<int>("LeasingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LeasingStart");

                    b.Property<int>("UserId");

                    b.HasKey("LeasingId");

                    b.HasIndex("UserId");

                    b.ToTable("Leasings");
                });

            modelBuilder.Entity("LeasingCore.Models.LeasingDetail", b =>
                {
                    b.Property<int>("LeasingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LeasingDetailAmount");

                    b.Property<DateTime>("LeasingDetailEnd");

                    b.Property<bool>("LeasingDetailExtend");

                    b.Property<int>("LeasingId");

                    b.Property<int?>("ProductId");

                    b.HasKey("LeasingDetailId");

                    b.HasIndex("LeasingId");

                    b.HasIndex("ProductId");

                    b.ToTable("LeasingDetails");
                });

            modelBuilder.Entity("LeasingCore.Models.Param", b =>
                {
                    b.Property<int>("ParamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ParamId");

                    b.ToTable("Params");
                });

            modelBuilder.Entity("LeasingCore.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhotoUrl")
                        .IsRequired();

                    b.HasKey("PhotoId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("LeasingCore.Models.PhotoProduct", b =>
                {
                    b.Property<int>("PhotoProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PhotoId");

                    b.Property<bool>("PhotoProductIsDefault");

                    b.Property<int>("ProductId");

                    b.HasKey("PhotoProductId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("ProductId");

                    b.ToTable("PhotoProducts");
                });

            modelBuilder.Entity("LeasingCore.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("ProductAdded");

                    b.Property<int>("ProductAvailability");

                    b.Property<string>("ProductCode")
                        .IsRequired();

                    b.Property<string>("ProductDescription");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<decimal>("ProductPrice");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LeasingCore.Models.ProductAssortment", b =>
                {
                    b.Property<int>("ProductAssortmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssortmentId");

                    b.Property<int>("ProductId");

                    b.HasKey("ProductAssortmentId");

                    b.HasIndex("AssortmentId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAssortments");
                });

            modelBuilder.Entity("LeasingCore.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LeasingDetailId");

                    b.Property<DateTime>("ReportAdded");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("StatusId");

                    b.HasKey("ReportId");

                    b.HasIndex("LeasingDetailId");

                    b.HasIndex("StatusId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("LeasingCore.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LeasingCore.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("LeasingCore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<int>("RoleId");

                    b.Property<string>("UserEmail");

                    b.Property<string>("UserFirstName")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("UserPassword")
                        .HasMaxLength(20);

                    b.Property<string>("UserSurname")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeasingCore.Models.Assortment", b =>
                {
                    b.HasOne("LeasingCore.Models.Param", "Param")
                        .WithMany("Assortments")
                        .HasForeignKey("ParamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LeasingCore.Models.Leasing", b =>
                {
                    b.HasOne("LeasingCore.Models.User", "User")
                        .WithMany("Leasings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LeasingCore.Models.LeasingDetail", b =>
                {
                    b.HasOne("LeasingCore.Models.Leasing", "Leasing")
                        .WithMany("LeasingDetails")
                        .HasForeignKey("LeasingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LeasingCore.Models.Product", "Product")
                        .WithMany("LeasingDetails")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("LeasingCore.Models.PhotoProduct", b =>
                {
                    b.HasOne("LeasingCore.Models.Photo", "Photo")
                        .WithMany("PhotoProducts")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LeasingCore.Models.Product", "Product")
                        .WithMany("PhotoProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LeasingCore.Models.Product", b =>
                {
                    b.HasOne("LeasingCore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LeasingCore.Models.ProductAssortment", b =>
                {
                    b.HasOne("LeasingCore.Models.Assortment", "Assortment")
                        .WithMany("ProductAssortments")
                        .HasForeignKey("AssortmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LeasingCore.Models.Product", "Product")
                        .WithMany("ProductAssortments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LeasingCore.Models.Report", b =>
                {
                    b.HasOne("LeasingCore.Models.LeasingDetail", "LeasingDetail")
                        .WithMany("Reports")
                        .HasForeignKey("LeasingDetailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LeasingCore.Models.Status", "Status")
                        .WithMany("Reports")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LeasingCore.Models.User", b =>
                {
                    b.HasOne("LeasingCore.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LeasingCore.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
